{% set name = "osx-sysroot" %}
{% set version = "2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1
  {% if cross_target_platform == "osx-arm64" and _MACOSX_DEPLOYMENT_TARGET_[0:2]|int < 11 %}
  skip: True
  {% endif %}

outputs:
  - name: macosx_deployment_target_{{ cross_target_platform }}
    version: "{{ _MACOSX_DEPLOYMENT_TARGET_ }}"
    script: build_mdt.sh
    build:
      noarch: generic
      run_exports:
        strong:
{% if cross_target_platform != "osx-arm64" or _MACOSX_DEPLOYMENT_TARGET_ != "11.0" %}
          - __osx >={{ _MACOSX_DEPLOYMENT_TARGET_ }}
{% endif %}
    test:
      commands:
        - "[[ ${MACOSX_DEPLOYMENT_TARGET} == '{{ _MACOSX_DEPLOYMENT_TARGET_ }}' ]]"

about:
  home: https://github.com/conda-forge/osx-sysroot-feedstock
  summary: metapackage to set the MACOSX_DEPLOYMENT_TARGET
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
    - xhochy
